[tools]
python = "3.11"

[tasks.update_exec]
description = "Commit exercises"
usage = '''
arg "<input>" {
  help "Type of exercise"
  long_help """
  The input file should be in JSON or YAML format.

  Supported schemas:
  - dsa: dsa exercises
  - data: data exercises

  Example:
    mise run update dsa
  """
}
arg "<message>" {
  help "commit message"
}
'''

run = [
    "git add .",
    'git commit -m "${usage_input?}: ${usage_message?}"',
    "git push origin master"
]
