[tools]
python = "3.11"

[tasks.update_exec]
description = "Commit exercises"
usage = '''
arg "<message>" {
  help "commit message"
}
'''

run = [
    "git add .",
    'git commit -m "${usage_message?}"',
    "git push origin master"
]
